### ISSUE TITLE
Generated text doesn't appear in the text area

### ISSUE THREAD

**Issue by 90barricade93** [90barricade93/ai-joke-generator#1]
After selecting the options and pressing the generate button, the chat api communicates with the model and the model starts generating. 

The generated text doesn't appear in the text area.

I called the component in the page.tsx and worked in component joke-generator.tsx where I called the textarea component and added a default text and the result (I guess)

**Comment by MatheusDaros** [comment]
Hello @90barricade93 

The project is looking good!

Instead of having a text area just for the generated joke, wouldn't it be better to display the array of messages in a chat format?
Look how we did here: https://github.com/Encode-Club-AI-Bootcamp/Generative-AI-Applications/blob/main/Lesson-08/project/04-Story-Telling.md

This way you can use the SDK to handle it all for you.

**Comment by 90barricade93** [comment]
Thank you!,
Also for your reply.
Yes, I remember that app and i worked like a charm.
I have looked at it many times.
-I need to add the generate button to the page.tsx
Like this:

<button
  className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded disabled:opacity-50"
  disabled={isLoading || (!state.genre || !state.tone)}
  onClick={() =>
    append({
      role: "user",
      content: `Generate a ${state.genre} story in a ${state.tone} tone`,
    })
  }
>
  Generate Story
</button>
Include an element to display the generated story

Replace {/* chat messages code */} with the following code:
<div
  hidden={
    messages.length === 0 ||
    messages[messages.length - 1]?.content.startsWith("Generate")
  }
  className="bg-opacity-25 bg-gray-700 rounded-lg p-4"
>
  {messages[messages.length - 1]?.content}
</div>

**Comment by MatheusDaros** [comment]
Exactly.
In fact you can even pick the complete code at the end and adapt for the joke generator to use it as a base.

**Comment by 90barricade93** [comment]
Perfect, I start to get it ;)
See you soon!
